version: '3.8'
services:
  my_wallet:
    container_name: "my_wallet"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db_wallet

  db_wallet:
    container_name: "db_wallet"
    image: postgres:14.3-alpine
    hostname: db_wallet
    volumes:
      - postgresql_wallet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'wallet_db'
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  postgresql_wallet: