version: '3.8'
services:
  my_wallet:
    container_name: "my_wallet"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
      - /home/vr/Downloads/excel/:/usr/src/app2
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db_wallet

  db_wallet:
    container_name: "db_wallet"
    image: postgres:14.3-alpine
    hostname: db_wallet
    volumes:
      - postgresql_wallet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'wallet_db'
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
#  mysql_wallet:
#    container_name: "mysql_wallet"
#    image: mysql:8.0.27
#    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - mysql_wallet:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: realtor_db
#      MYSQL_DATABASE: wallet
#    ports:
#      - "3306:3306"


volumes:
  postgresql_wallet:
  mysql_wallet: