# Generated by Django 4.1 on 2022-11-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('type', models.CharField(choices=[('checking_account', 'Conta Corrente'), ('fixed_investment_account', 'Investimento renda fixa'), ('variable_investment_account', 'Investimento renda variável'), ('saving_account', 'Reservas')], max_length=50, unique=True, verbose_name='Tipo de conta')),
                ('description', models.CharField(blank=True, default=None, max_length=999, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cota')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor atual da cota')),
            ],
        ),
        migrations.CreateModel(
            name='VariableInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('number_of_shares', models.IntegerField(default=1, verbose_name='Número de cotas')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wallet_app.account')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_transaction', to='wallet_app.share')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('category', models.CharField(choices=[('monthly_deposit', 'Depósito mensal'), ('revenue', 'Rendimento'), ('loss', 'Retirada'), ('Other', 'Outro')], max_length=50, unique=True, verbose_name='Categoria')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wallet_app.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('category', models.CharField(choices=[('Receipts', 'Recebimentos'), ('purchases', 'Compras'), ('yield', 'Rendimentos'), ('refund', 'Reembolso'), ('dwelling', 'Moradia'), ('pharmacy', 'Farmácia'), ('bills', 'Contas'), ('grocery', 'Mercado'), ('food', 'Alimentação'), ('travel', 'Viagem'), ('health', 'Saúde'), ('study', 'Estudo'), ('Mother', 'Mãe'), ('transport', 'Transporte'), ('game', 'Jogo'), ('leisure', 'Lazer'), ('balance', 'Saldo +/-'), ('others', 'Outros')], max_length=50, unique=True, verbose_name='Categoria')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wallet_app.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('projected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Projetado')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rentabilidade')),
                ('category', models.CharField(choices=[('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro_ipca', 'Tesouro IPCA'), ('tesouro_selic', 'Tesouro Selic'), ('tesouro_prefix', 'Tesouro Prefixado')], max_length=50, unique=True, verbose_name='Categoria')),
                ('obs', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='wallet_app.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
