# Generated by Django 4.1 on 2022-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('receipts', 'Recebimentos'), ('purchases', 'Compras'), ('yield', 'Rendimentos'), ('refund', 'Reembolso'), ('dwelling', 'Moradias'), ('pharmacy', 'Farmácia'), ('bills', 'Contas'), ('grocery', 'Mercado'), ('food', 'Alimentação'), ('travel', 'Viagem'), ('health', 'Saúde'), ('study', 'Estudo'), ('mother', 'Mãe'), ('transport', 'Transporte'), ('game', 'Jogo'), ('leisure', 'Lazer'), ('balance', 'Saldo +/-'), ('others', 'Outros')], max_length=100, verbose_name='Categoria'),
        ),
    ]
