# Generated by Django 4.1 on 2022-11-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('receipts', 'Recebimentos'), ('purchases', 'Compras'), ('credit_card', 'Cartão'), ('yield', 'Rendimentos'), ('refund', 'Reembolso'), ('dwelling', 'Moradias'), ('pharmacy', 'Farmácia'), ('bills', 'Contas'), ('grocery', 'Mercado'), ('food', 'Alimentação'), ('travel', 'Viagem'), ('health', 'Saúde'), ('study', 'Estudo'), ('mother', 'Mãe'), ('transport', 'Transporte'), ('game', 'Jogo'), ('leisure', 'Lazer'), ('pet', 'Pet'), ('balance', 'Saldo +/-'), ('others', 'Outros')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('revenue', 'Rendimentos'), ('loss', 'Retirada'), ('Other', 'Outro')], max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
