# Generated by Django 4.1 on 2022-11-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0004_alter_monthlyexpense_category_alter_saving_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedinvestment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variableinvestment',
            name='name',
        ),
    ]
