# Generated by Django 4.1 on 2022-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_remove_fixedinvestment_name_remove_saving_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('revenue', 'Rendimentos'), ('loss', 'Retirada'), ('Other', 'Outro')], max_length=50, verbose_name='Categoria'),
        ),
    ]
