# Generated by Django 4.1 on 2022-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0006_alter_saving_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedinvestment',
            name='profitability',
            field=models.FloatField(verbose_name='Rentabilidade'),
        ),
    ]
