# Generated by Django 4.1 on 2022-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0007_alter_fixedinvestment_profitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedinvestment',
            name='category',
            field=models.CharField(choices=[('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro_ipca', 'Tesouro IPCA'), ('tesouro_selic', 'Tesouro Selic'), ('tesouro_prefix', 'Tesouro Prefixado')], max_length=50, verbose_name='Categoria'),
        ),
    ]
