# Generated by Django 4.1 on 2022-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0008_alter_fixedinvestment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo'),
        ),
    ]
