# Generated by Django 4.1 on 2022-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0009_monthlyexpense_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default='White', max_length=100, verbose_name='Cor'),
        ),
    ]
