# Generated by Django 4.1 on 2022-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0010_account_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking_account', 'Conta Corrente'), ('fixed_investment_account', 'Investimento renda fixa'), ('variable_investment_account', 'Investimento renda variável'), ('saving_account', 'Reservas')], max_length=50, verbose_name='Tipo de conta'),
        ),
    ]
