# Generated by Django 4.1 on 2023-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0011_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.CharField(choices=[('imobiliary funds', 'Fundos Imobiliarios'), ('capital_shares', 'Ações')], default=None, max_length=50, verbose_name='Tipo de ação'),
        ),
    ]
