# Generated by Django 4.1 on 2023-01-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0013_alter_share_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('receipts', 'Recebimentos'), ('purchases', 'Compras'), ('credit_card', 'Cartão'), ('yield', 'Rendimentos'), ('refund', 'Reembolso'), ('dwelling', 'Moradias'), ('pharmacy', 'Farmácia'), ('bills', 'Contas'), ('grocery', 'Mercado'), ('food', 'Alimentação'), ('travel', 'Viagem'), ('health', 'Saúde'), ('study', 'Estudo'), ('mother', 'Mãe'), ('transport', 'Transporte'), ('game', 'Jogo'), ('leisure', 'Lazer'), ('pet', 'Pet'), ('balance', 'Saldo +/-'), ('others', 'Outros'), ('account_transfer', 'Transferência')], max_length=100, verbose_name='Categoria'),
        ),
    ]
