# Generated by Django 4.1 on 2023-01-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0014_indexes_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexes',
            name='is_percent',
            field=models.BooleanField(default=False),
        ),
    ]
