# Generated by Django 4.1 on 2023-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0015_indexes_is_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedinvestment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='saving',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Saldo'),
        ),
    ]
