# Generated by Django 4.1 on 2023-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0017_buyinglist_alter_monthlyexpense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='Fonte da renda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da renda')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(max_length=100, verbose_name='Distribuição da renda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor distribuido')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='Item')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('category', models.CharField(choices=[('work', 'Trabalho'), ('study', 'Estudo'), ('personal', 'Pessoal'), ('home', 'Casa'), ('Health', 'Saúde')], max_length=150, verbose_name='Categoria')),
            ],
        ),
    ]
