# Generated by Django 4.1 on 2023-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0018_income_incomedistribution_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, verbose_name='Nível de prioridade'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(choices=[('work', 'Trabalho'), ('study', 'Estudo'), ('personal', 'Pessoal'), ('home', 'Casa'), ('health', 'Saúde'), ('others', 'Outros')], max_length=150, verbose_name='Categoria'),
        ),
    ]
