# Generated by Django 4.1 on 2023-04-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0019_todolist_priority_alter_todolist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data de Referência')),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Total')),
            ],
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('revenue', 'Rendimentos'), ('withdrawl', 'Retirada'), ('Other', 'Outro')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Nível de prioridade'),
        ),
    ]
