# Generated by Django 4.1 on 2023-11-20 22:38

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0020_networth_remove_todolist_date_alter_saving_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeScaleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
