# Generated by Django 4.1 on 2023-11-20 22:48

from django.db import migrations
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0021_timescaleshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescaleshare',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day'),
        ),
    ]
